#!/usr/bin/with-contenv sh

cd /app/sonarr/bin

if [ -z "${LSIO_NON_ROOT_USER}" ]; then
    exec s6-notifyoncheck -d -n 300 -w 1000 \
        s6-setuidgid abc /app/sonarr/bin/Sonarr \
        -nobrowser -data=/config
else
    exec s6-notifyoncheck -d -n 300 -w 1000 \
        /app/sonarr/bin/Sonarr \
        -nobrowser -data=/config
fi
